name: Console

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:

    Build:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
        
      - name: Restore NuGet 
        run: |
          nuget restore **/**.sln
          
      - name: Build Console App
        run: |              
          consoleCSProj=`find -name RedditStats.Console.csproj`
          echo consoleCSProj $consoleCSProj

          dotnet build -c Release $consoleCSProj