name: Functions

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:

    Build_Functions:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        
      - name: Restore NuGet 
        run: |
          dotnet restore **/**.sln
          
      - name: Build Functions App
        run: |              
          functionsCSProj=`find . -name RedditStats.Functions.csproj`
          echo functionsCSProj $functionsCSProj

          dotnet build -c Release $functionsCSProj
